trainset_3d: ['Human36M']
trainset_2d: []
testset: 'PW3D'

lr_dec_epoch: [30]
end_epoch: 40
lr: 0.001
lr_backbone: 0.001
lr_dec_factor: 10

# modify batch size
train_batch_size: 128
test_batch_size: 128
